 export default cookie = [{
         "domain": ".youtube.com",
         "expirationDate": 1754578408.051243,
         "hostOnly": false,
         "httpOnly": false,
         "name": "__Secure-1PAPISID",
         "path": "/",
         "sameSite": "unspecified",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "fKLEBG-K7rNqn2dR/ADNBGY-dtscUPoTDW",
         "id": 1
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1754578408.05159,
         "hostOnly": false,
         "httpOnly": true,
         "name": "__Secure-1PSID",
         "path": "/",
         "sameSite": "unspecified",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "g.a000lQg6T-wzEyloZfq17EYjTLB0_HTsJ-U3s6bHi-iG1-48-zco6tSLrNaM9VSipNBuA4ItwwACgYKAWcSARQSFQHGX2MiGN9QgCGscoFhbFJIWPYUPxoVAUF8yKpdp3J6H0EIvkkvogdds7-j0076",
         "id": 2
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1753346019.21302,
         "hostOnly": false,
         "httpOnly": true,
         "name": "__Secure-1PSIDCC",
         "path": "/",
         "sameSite": "unspecified",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "AKEyXzUrnh3lRyxyiZ-oqnRrOTS5IcIdz3qSLYfFfyoO16yIYJqAjTS_tyQMVzfFxO6_MSihwqs",
         "id": 3
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1753345930.261829,
         "hostOnly": false,
         "httpOnly": true,
         "name": "__Secure-1PSIDTS",
         "path": "/",
         "sameSite": "unspecified",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "sidts-CjEB4E2dkVUYaHCJgpcEA4Y1recyKC-oxnbu7Hfs3ShmFKgynhw0-yXzksk6P1J5e4hwEAA",
         "id": 4
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1754578408.051278,
         "hostOnly": false,
         "httpOnly": false,
         "name": "__Secure-3PAPISID",
         "path": "/",
         "sameSite": "no_restriction",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "fKLEBG-K7rNqn2dR/ADNBGY-dtscUPoTDW",
         "id": 5
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1754578408.051638,
         "hostOnly": false,
         "httpOnly": true,
         "name": "__Secure-3PSID",
         "path": "/",
         "sameSite": "no_restriction",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "g.a000lQg6T-wzEyloZfq17EYjTLB0_HTsJ-U3s6bHi-iG1-48-zcoXqK-cOSOqVnthu8wavpQVAACgYKARASARQSFQHGX2Mi_YaDgkfipaZ5vIODOVYY9xoVAUF8yKpyDZMEYaUOf1sbAUuOTLBf0076",
         "id": 6
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1753346019.213075,
         "hostOnly": false,
         "httpOnly": true,
         "name": "__Secure-3PSIDCC",
         "path": "/",
         "sameSite": "no_restriction",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "AKEyXzUzfW-X1TeagtOTg5cqC0icLQqujeo7vKxs0qXV7uXSDZV4_GTB-qPN8fxYcQ-nPwtfCg",
         "id": 7
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1753345930.261942,
         "hostOnly": false,
         "httpOnly": true,
         "name": "__Secure-3PSIDTS",
         "path": "/",
         "sameSite": "no_restriction",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "sidts-CjEB4E2dkVUYaHCJgpcEA4Y1recyKC-oxnbu7Hfs3ShmFKgynhw0-yXzksk6P1J5e4hwEAA",
         "id": 8
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1754578408.051159,
         "hostOnly": false,
         "httpOnly": false,
         "name": "APISID",
         "path": "/",
         "sameSite": "unspecified",
         "secure": false,
         "session": false,
         "storeId": "0",
         "value": "bXta7P0Tl4qcR7R3/AbJsI4l_697TNEBsb",
         "id": 9
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1754578408.051003,
         "hostOnly": false,
         "httpOnly": true,
         "name": "HSID",
         "path": "/",
         "sameSite": "unspecified",
         "secure": false,
         "session": false,
         "storeId": "0",
         "value": "AaSTHVPZSXEMXTQgI",
         "id": 10
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1755273082.304073,
         "hostOnly": false,
         "httpOnly": true,
         "name": "LOGIN_INFO",
         "path": "/",
         "sameSite": "no_restriction",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "AFmmF2swRQIgfGxcOCRy0ThSN_Ar-cEbZ4fUinu9Ni7s9l9jTKXywOECIQCgg24roMIs3qdsiX9-MuLsIANH91AOvhfBHC8Niw0TCw:QUQ3MjNmelBHaVlfRklya3YzWWJ5U1FDMkhuci1YUUR4RjZBRVFmWmFJcGRla2o3ZUV6M2dUcUFZWnlmZlZtLUppNDdVQURoQVNpa2JZcy1EVWxtZWptY25obTV1Z0pjVEZjNTJQZVFIMURNQXRSNzRYeEhpc3hieVpvSkh2RnRzQ3BvNVd5Q19ackpIQ3ZBS2xLSUJVMnRYMUJ1WUZCdUx3",
         "id": 11
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1756369991.339937,
         "hostOnly": false,
         "httpOnly": false,
         "name": "PREF",
         "path": "/",
         "sameSite": "unspecified",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "f6=40000000&f7=4100&tz=Europe.Paris&f4=4000000&f5=30000",
         "id": 12
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1754578408.051195,
         "hostOnly": false,
         "httpOnly": false,
         "name": "SAPISID",
         "path": "/",
         "sameSite": "unspecified",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "fKLEBG-K7rNqn2dR/ADNBGY-dtscUPoTDW",
         "id": 13
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1754578408.051542,
         "hostOnly": false,
         "httpOnly": false,
         "name": "SID",
         "path": "/",
         "sameSite": "unspecified",
         "secure": false,
         "session": false,
         "storeId": "0",
         "value": "g.a000lQg6T-wzEyloZfq17EYjTLB0_HTsJ-U3s6bHi-iG1-48-zcoBmYuOcp0QJZ_hpgsI6B_-wACgYKAQ0SARQSFQHGX2Mi_xRAEzqp3BDRRoY2JEDcehoVAUF8yKqAPYdBjp3ejlDoXnsK1Wk90076",
         "id": 14
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1753346019.212902,
         "hostOnly": false,
         "httpOnly": false,
         "name": "SIDCC",
         "path": "/",
         "sameSite": "unspecified",
         "secure": false,
         "session": false,
         "storeId": "0",
         "value": "AKEyXzVYI12-vC7a2boP4HvsJlznVMP_8mp_awoC-rOZlfOj7AzwklsG2SPTDMDIhetinlLK6VQ",
         "id": 15
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1754578408.05112,
         "hostOnly": false,
         "httpOnly": true,
         "name": "SSID",
         "path": "/",
         "sameSite": "unspecified",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "A-CluoUGPSBck41oc",
         "id": 16
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1725722543.000628,
         "hostOnly": false,
         "httpOnly": true,
         "name": "VISITOR_PRIVACY_METADATA",
         "path": "/",
         "sameSite": "no_restriction",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "CgJGUhIIEgQSAgsMIDs%3D",
         "id": 17
     }
 ]