 export default cookie = [{
         "domain": ".youtube.com",
         "expirationDate": 1757171145.726707,
         "hostOnly": false,
         "httpOnly": false,
         "name": "__Secure-1PAPISID",
         "path": "/",
         "sameSite": "unspecified",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "fKLEBG-K7rNqn2dR/ADNBGY-dtscUPoTDW",
         "id": 1
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1757171145.726984,
         "hostOnly": false,
         "httpOnly": true,
         "name": "__Secure-1PSID",
         "path": "/",
         "sameSite": "unspecified",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "g.a000mgg6T5hcc-l2a7BwzBu5CHvQTRHU_8wk6EExj_UQv53WMUEJ_2gjdKo0a2IqKNTtW5jLAwACgYKAbgSARQSFQHGX2MirKdZX08Db3GtQIN4T6IVnxoVAUF8yKoft2gevYyGdjPKSpSTCpDb0076",
         "id": 2
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1754466104.237467,
         "hostOnly": false,
         "httpOnly": true,
         "name": "__Secure-1PSIDCC",
         "path": "/",
         "sameSite": "unspecified",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "AKEyXzU9_QftQcNl8Xtya8QJxMN9psGutqqrN5p9gQJ8LucpIaKBA4xK3Nis4IHDQK_2C8n-UMw",
         "id": 3
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1754385332.238839,
         "hostOnly": false,
         "httpOnly": true,
         "name": "__Secure-1PSIDTS",
         "path": "/",
         "sameSite": "unspecified",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "sidts-CjEB4E2dkVGmSVKA-BHWP6vr46iB29eU5e4SHkvZn8t_Xb9a-6x4cxLW4RZGqckpQQ2fEAA",
         "id": 4
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1757171145.726752,
         "hostOnly": false,
         "httpOnly": false,
         "name": "__Secure-3PAPISID",
         "path": "/",
         "sameSite": "no_restriction",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "fKLEBG-K7rNqn2dR/ADNBGY-dtscUPoTDW",
         "id": 5
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1757171145.727008,
         "hostOnly": false,
         "httpOnly": true,
         "name": "__Secure-3PSID",
         "path": "/",
         "sameSite": "no_restriction",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "g.a000mgg6T5hcc-l2a7BwzBu5CHvQTRHU_8wk6EExj_UQv53WMUEJVceFz5h2Ldl-Nr644buKmQACgYKAYASARQSFQHGX2MiSm4cXqCUdWQyRtfieFoYixoVAUF8yKqO0Qnjbm4F1VdnHLfjrwAF0076",
         "id": 6
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1754466104.237507,
         "hostOnly": false,
         "httpOnly": true,
         "name": "__Secure-3PSIDCC",
         "path": "/",
         "sameSite": "no_restriction",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "AKEyXzXxVH9ffOf8eDt1BKHwDtOdjI8aHQiAgZJDHY9lHRgYws3iS6ooKIp-038vav9C5J40bg",
         "id": 7
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1754385332.238945,
         "hostOnly": false,
         "httpOnly": true,
         "name": "__Secure-3PSIDTS",
         "path": "/",
         "sameSite": "no_restriction",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "sidts-CjEB4E2dkVGmSVKA-BHWP6vr46iB29eU5e4SHkvZn8t_Xb9a-6x4cxLW4RZGqckpQQ2fEAA",
         "id": 8
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1757171145.726617,
         "hostOnly": false,
         "httpOnly": false,
         "name": "APISID",
         "path": "/",
         "sameSite": "unspecified",
         "secure": false,
         "session": false,
         "storeId": "0",
         "value": "bXta7P0Tl4qcR7R3/AbJsI4l_697TNEBsb",
         "id": 9
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1757171145.726467,
         "hostOnly": false,
         "httpOnly": true,
         "name": "HSID",
         "path": "/",
         "sameSite": "unspecified",
         "secure": false,
         "session": false,
         "storeId": "0",
         "value": "AaSTHVPZSXEMXTQgI",
         "id": 10
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1755273082.304073,
         "hostOnly": false,
         "httpOnly": true,
         "name": "LOGIN_INFO",
         "path": "/",
         "sameSite": "no_restriction",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "AFmmF2swRQIgfGxcOCRy0ThSN_Ar-cEbZ4fUinu9Ni7s9l9jTKXywOECIQCgg24roMIs3qdsiX9-MuLsIANH91AOvhfBHC8Niw0TCw:QUQ3MjNmelBHaVlfRklya3YzWWJ5U1FDMkhuci1YUUR4RjZBRVFmWmFJcGRla2o3ZUV6M2dUcUFZWnlmZlZtLUppNDdVQURoQVNpa2JZcy1EVWxtZWptY25obTV1Z0pjVEZjNTJQZVFIMURNQXRSNzRYeEhpc3hieVpvSkh2RnRzQ3BvNVd5Q19ackpIQ3ZBS2xLSUJVMnRYMUJ1WUZCdUx3",
         "id": 11
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1757490101.764734,
         "hostOnly": false,
         "httpOnly": false,
         "name": "PREF",
         "path": "/",
         "sameSite": "unspecified",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "f6=40000000&f7=4100&tz=Europe.Paris&f4=4000000&f5=30000",
         "id": 12
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1757171145.726662,
         "hostOnly": false,
         "httpOnly": false,
         "name": "SAPISID",
         "path": "/",
         "sameSite": "unspecified",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "fKLEBG-K7rNqn2dR/ADNBGY-dtscUPoTDW",
         "id": 13
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1757171145.72696,
         "hostOnly": false,
         "httpOnly": false,
         "name": "SID",
         "path": "/",
         "sameSite": "unspecified",
         "secure": false,
         "session": false,
         "storeId": "0",
         "value": "g.a000mgg6T5hcc-l2a7BwzBu5CHvQTRHU_8wk6EExj_UQv53WMUEJ96rZRpC1Z2lE_B_xhDaedQACgYKAc4SARQSFQHGX2MiWo7DfdbBzTAZI-nne3M7IhoVAUF8yKqzFJ6KFzrqGzrBZ_Zizd7g0076",
         "id": 14
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1754466104.237361,
         "hostOnly": false,
         "httpOnly": false,
         "name": "SIDCC",
         "path": "/",
         "sameSite": "unspecified",
         "secure": false,
         "session": false,
         "storeId": "0",
         "value": "AKEyXzUH7t_y591g5VlXU93My6LpMOc8xZOJs82Xq7F2CkeMQYWTSJtrggMqLnp3anslKmb7wQM",
         "id": 15
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1757171145.726566,
         "hostOnly": false,
         "httpOnly": true,
         "name": "SSID",
         "path": "/",
         "sameSite": "unspecified",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "A-CluoUGPSBck41oc",
         "id": 16
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1722930109,
         "hostOnly": false,
         "httpOnly": false,
         "name": "ST-3opvp5",
         "path": "/",
         "sameSite": "unspecified",
         "secure": false,
         "session": false,
         "storeId": "0",
         "value": "session_logininfo=AFmmF2swRQIgfGxcOCRy0ThSN_Ar-cEbZ4fUinu9Ni7s9l9jTKXywOECIQCgg24roMIs3qdsiX9-MuLsIANH91AOvhfBHC8Niw0TCw%3AQUQ3MjNmelBHaVlfRklya3YzWWJ5U1FDMkhuci1YUUR4RjZBRVFmWmFJcGRla2o3ZUV6M2dUcUFZWnlmZlZtLUppNDdVQURoQVNpa2JZcy1EVWxtZWptY25obTV1Z0pjVEZjNTJQZVFIMURNQXRSNzRYeEhpc3hieVpvSkh2RnRzQ3BvNVd5Q19ackpIQ3ZBS2xLSUJVMnRYMUJ1WUZCdUx3",
         "id": 17
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1722930107,
         "hostOnly": false,
         "httpOnly": false,
         "name": "ST-tladcw",
         "path": "/",
         "sameSite": "unspecified",
         "secure": false,
         "session": false,
         "storeId": "0",
         "value": "session_logininfo=AFmmF2swRQIgfGxcOCRy0ThSN_Ar-cEbZ4fUinu9Ni7s9l9jTKXywOECIQCgg24roMIs3qdsiX9-MuLsIANH91AOvhfBHC8Niw0TCw%3AQUQ3MjNmelBHaVlfRklya3YzWWJ5U1FDMkhuci1YUUR4RjZBRVFmWmFJcGRla2o3ZUV6M2dUcUFZWnlmZlZtLUppNDdVQURoQVNpa2JZcy1EVWxtZWptY25obTV1Z0pjVEZjNTJQZVFIMURNQXRSNzRYeEhpc3hieVpvSkh2RnRzQ3BvNVd5Q19ackpIQ3ZBS2xLSUJVMnRYMUJ1WUZCdUx3",
         "id": 18
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1722930108,
         "hostOnly": false,
         "httpOnly": false,
         "name": "ST-xuwub9",
         "path": "/",
         "sameSite": "unspecified",
         "secure": false,
         "session": false,
         "storeId": "0",
         "value": "session_logininfo=AFmmF2swRQIgfGxcOCRy0ThSN_Ar-cEbZ4fUinu9Ni7s9l9jTKXywOECIQCgg24roMIs3qdsiX9-MuLsIANH91AOvhfBHC8Niw0TCw%3AQUQ3MjNmelBHaVlfRklya3YzWWJ5U1FDMkhuci1YUUR4RjZBRVFmWmFJcGRla2o3ZUV6M2dUcUFZWnlmZlZtLUppNDdVQURoQVNpa2JZcy1EVWxtZWptY25obTV1Z0pjVEZjNTJQZVFIMURNQXRSNzRYeEhpc3hieVpvSkh2RnRzQ3BvNVd5Q19ackpIQ3ZBS2xLSUJVMnRYMUJ1WUZCdUx3",
         "id": 19
     },
     {
         "domain": ".youtube.com",
         "expirationDate": 1725722543.000628,
         "hostOnly": false,
         "httpOnly": true,
         "name": "VISITOR_PRIVACY_METADATA",
         "path": "/",
         "sameSite": "no_restriction",
         "secure": true,
         "session": false,
         "storeId": "0",
         "value": "CgJGUhIIEgQSAgsMIDs%3D",
         "id": 20
     }
 ]